version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - run: 
          pwd
          ls
      - checkout
      - run:
          name: To check some status
          command: |
            pwd
            ls -a
            export content=$(<main.py)
            echo "$content" > abc.txt
            echo "$content"
            ENV_VAR="$(cat main-test.py) | base64"
            echo "$ENV_VAR"
            cat abc.txt
            brew install jq && curl -O https://raw.githubusercontent.com/entria/slack-cli/master/src/slack && chmod +x slack
      - run:
          name: Run main file
          command: |
            pwd
            ls -a
            cat abc.txt
            echo "------------"
            echo "$(<main.py)"
            cat abc.txt
            echo "------------"
            echo "$content"
            echo "------------"
            echo "$ENV_VAR" | base64 --decode > ./main.py
            python3 main.py
      # - aws-s3/sync:
      #     arguments: |
      #       --acl public-read \
      #       --cache-control "max-age=86400"
      #     from: ~/project
      #     to: 's3://subhamdash123/'
      - aws-s3/copy:
          from: ./main.py
          to: 's3://subhamdash123/'
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - run: 
          pwd
          ls
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build