version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - run: 
          pwd
          ls
      - checkout
      - run:
          name: Run main file
          command: |
            pwd
            ls -a
            ~/
            python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build