version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID_DEV
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_DEV
          from: ./main.py
          to: 's3://subhamdash123/'

workflows:
  build_and_test:
    jobs:
      - build