version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    environment: 
      DATA_FILE: "$(cat main-test.py) | base64"
    steps:
      - run: 
          pwd
          ls
      - checkout 
      - run: 
          name: set up env variable
          command: |
            echo 'export DATA_FILE_DATA=$(cat main-test.py)' >> $BASH_ENV
            echo 'export DATA_FILE_1=$(cat README.md)' >> $BASH_ENV
            echo "$DATA_FILE_DATA"
      - run:
          name: To check some status
          command: |
            pwd
            ls -a
            echo "$DATA_FILE_DATA"
            echo "----#"
            echo "$DATA_FILE_1"
            echo "----$"
            export content=$(<main.py)
            echo "$content" > abc.txt
            echo "$content"
            export ENV_VAR="$(cat main-test.py) | base64"
            echo "$ENV_VAR"
            cat abc.txt
      - run:
          name: Run main file
          command: |
            pwd
            ls -a
            cat abc.txt
            echo $DATA_FILE
            echo "------------000000"
            echo "$DATA_FILE_DATA"
            echo "------------1111111"
            echo "$(<main.py)"
            cat abc.txt
            echo "------------222222222"
            echo "$content"
            echo "------------333333333"
            echo "$ENV_VAR"
            python3 main.py
      # - aws-s3/sync:
      #     arguments: |
      #       --acl public-read \
      #       --cache-control "max-age=86400"
      #     from: ~/project
      # #     to: 's3://subhamdash123/'
      - aws-s3/copy:
          from: ./main.py
          to: 's3://subhamdash123/'
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: 
          pwd
          ls
      - checkout
      - run: 
          name: install slack cli
          command: |
            brew install jq && curl -O https://raw.githubusercontent.com/entria/slack-cli/master/src/slack && chmod +x slack

workflows:
  build_and_test:
    jobs:
      - build
      - test